#!/usr/bin/env python
# -*- coding: utf-8 -*-

from sensors.core import load_config_file, run_probes


if __name__ == '__main__':
    config = load_config_file()
    print(run_probes(config['probes']))
