#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sys

from sensors.core import load_config, run_probes


if __name__ == '__main__':
    config_file = None
    try:
        config_file = sys.argv[1]
    except:
        pass
    config = load_config(config_file)
    print(run_probes(config['probes']))
